# npm publish workflow for loom-shuttle (standalone repository)
# Move this to .github/workflows/npm-publish.yml after repo split
#
# This workflow is manually triggered to publish to npm.
# It should only be run after a successful release.

name: npm Publish

on:
  workflow_dispatch:
    inputs:
      dry_run:
        description: 'Dry run (do not actually publish)'
        required: false
        default: 'true'
        type: choice
        options:
          - 'true'
          - 'false'

jobs:
  publish:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: write  # For npm provenance

    steps:
      - name: Checkout code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Setup Node.js
        uses: actions/setup-node@39370e3970a6d050c480ffad4ff0ed4d3fdee5af # v4.1.0
        with:
          node-version: 20
          registry-url: 'https://registry.npmjs.org'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Run tests
        run: npm test

      - name: Get package version
        id: version
        run: |
          VERSION=$(node -p "require('./package.json').version")
          echo "version=$VERSION" >> $GITHUB_OUTPUT
          echo "Package version: $VERSION"

      - name: Check if version already published
        id: check
        run: |
          PACKAGE_NAME=$(node -p "require('./package.json').name")
          VERSION="${{ steps.version.outputs.version }}"

          if npm view "${PACKAGE_NAME}@${VERSION}" version 2>/dev/null; then
            echo "Version $VERSION already published"
            echo "already_published=true" >> $GITHUB_OUTPUT
          else
            echo "Version $VERSION not yet published"
            echo "already_published=false" >> $GITHUB_OUTPUT
          fi

      - name: Publish to npm (dry run)
        if: inputs.dry_run == 'true'
        run: |
          echo "=== DRY RUN ==="
          npm publish --dry-run --access public
          echo "=== DRY RUN COMPLETE ==="

      - name: Publish to npm
        if: inputs.dry_run == 'false' && steps.check.outputs.already_published == 'false'
        run: npm publish --access public --provenance
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Skip publish (already published)
        if: inputs.dry_run == 'false' && steps.check.outputs.already_published == 'true'
        run: |
          echo "Skipping publish: version ${{ steps.version.outputs.version }} already exists on npm"
          exit 0
